# -*- coding: utf-8 -*-
"""find_duplicate_images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xA2k1R5uU2REwTQLr65J21CyAL6Horo2
"""

from google.colab import drive
drive.mount('/content/drive')

pip install difPy

from difPy import dif

search = dif('/content/drive/MyDrive/insects data/Ladybird', show_output=True, delete=True)

search = dif('/content/drive/MyDrive/insects data/Butterfly', show_output=True, delete=True)

search = dif('/content/drive/MyDrive/insects data/Dragonfly', show_output=True, delete=True)

search = dif('/content/drive/MyDrive/insects data/Grasshopper', show_output=True, delete=True)

search = dif('/content/drive/MyDrive/insects data/Mosquito', show_output=True, delete=True)